server:
  port: 5000

spring:
  main:
    allow-bean-definition-overriding: true
  datasource:
    url: jdbc:mysql://localhost:3306/reporttest?useLegacyDatetimeCode=false&useUnicode=true&characterEncoding=utf8&characterSetResults=utf8&useSSL=false&allowPublicKeyRetrieval=true
    username: test
    password: test
    initialization-mode: never
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect  ## org.hibernate.dialect.MySQL5InnoDBDialect
      format_sql: false
    show_sql: false
  data:
    mongodb:
      uri: mongodb://mongdbhost:27017/test

dongguan:
  account:
    accessId: a
    accessPwd: a
  report:
    url: bzfw.dg.cn/import/chuzhuwu
scheduled:
  houseTime: 0 0 * * * ?
  tenantTime: 0 10 * * * ?
  authTime: 0 10 * * * ?
  recordTime: 0 10 * * * ?
  terminalTime: 0 10 * * * ?